Task 1 but ticket 3
hedieh623/my-fe-super-duper-cool-app pull request #1
Opened 2022-09-26 14:24 UTC by hedieh623

2022-09-26 14:35 UTC, Augs0 requested changes
This is a good start, but there's some incorrect syntax and lots of components created that don't need to exist yet e.g. Comments. Try not to jump ahead to other tickets. Please fix the mistakes so we are able to see your articles rendered

2022-09-26 14:35 UTC, Augs0 commented on src/App.js
> +  const [articles, setArticles] = { useState };
This isn't the correct way to use useState. It should be useState() with the default data inside of the round brackets e.g. useState([])

2022-09-26 14:35 UTC, Augs0 commented on src/Components/Header.jsx
> +  return <h1> Northcoders News</h1>;
It would be good to use <header> around this h1

2022-09-26 14:35 UTC, Augs0 commented on src/Components/Topics.jsx
> +      .get(`https://my-fe-super-duper-cool-app.herokuapp.com/=${articles}`)
The use of articles as your prop here is very confusing in a topics component

2022-09-26 14:35 UTC, Augs0 commented
Please also add a screenshot of your plan so other mentors can see it :)

2022-09-27 11:38 UTC, hedieh623 commented
![2022-09-27](https://user-images.githubusercontent.com/63189792/192515461-fcde850f-37c3-443c-8088-6788a158f5fb.png)

2022-09-27 12:48 UTC, yangalexyangg commented on src/Components/Articles.jsx
> +        console.log(data.articles);
remove this console.log

2022-09-27 12:50 UTC, yangalexyangg commented on src/Components/Articles.jsx
> +          return <li key={article.article_id}>{article.title}</li>;
You haven't added anything more such as the author, date, votes or body

2022-09-27 12:52 UTC, yangalexyangg requested changes
See the comments I have added. Also you need to delete all of the components you are not using

2022-09-27 13:25 UTC, leekli approved these changes
Hi Hedieh, I can see you've made the changes to this.

I'm technically happy to sign this off as it adheres to the task, however I would say it's not displayed in the best way it could it, at the moment it's a simple list of article titles, separated by date and author with commas. It's not the easiest to read.

You are free to merge this branch, however as you move to your next ticket I would encourage you to spend some time having a think about how to present the info to the user in a nice, easy to see way.

2022-09-28 07:42 UTC, merged